# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-lifx-lib.spec

# add or remove files that should be synced
synced_files:
    - python-lifx-lib.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: lifx-lib
# downstream (Fedora) RPM package name
downstream_package_name: lifx-lib

upstream_project_url: https://github.com/majamassarini/lifx-lib

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets: fedora-stable
- job: copr_build
  trigger: commit
  metadata:
    targets: fedora-stable
