# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-lifx-lib.spec

upstream_package_name: lifx-lib

upstream_project_url: https://github.com/majamassarini/lifx-lib

jobs:
- job: copr_build
  trigger: pull_request
  targets: fedora-all
